### ISSUE TITLE
[Request] Throwing out few ideas

### ISSUE THREAD

**Issue by DatCaptainHorse** [zenoverflow/omnichain#10]
Been spending last few days working with omnichain to test things out and see where it goes.
I noticed few things that I feel could be added/changed, hope it's fine to do feature/change requests!

#### Ideas
- PickXArrayItem - I feel it should accept `-1` as an index value for getting last element of an array.
- Chat/TextCompletion - It'd be nice to be able to use common model and settings for multiple of such nodes, perhaps new Model and/or Settings nodes?
- New node for replacing substrings in text, with regex version. Parameters for limiting count of replacements done and a starting index.

**Comment by zenoverflow** [comment]
Those are all good suggestions.

- Negative indices aren't a thing in JS array access, so I hadn't considered it, but I should be able to modify the code for the existing nodes to support this without breaking existing workflows.
- I could add an override property for each type of completion node. If I make it accept an arbitrary JSON object, it would even allow for workflows where a model modifies its own settings. I'll see if this can be added in-place without breaking existing workflows, hopefully it's fine.
- Adding a replace node (+ regex version) is pretty straightforward with the settings you mentioned, so I'll definitely do that.

In regards to settings reuse (the 2nd idea), have you tried using the Module nodes? Those technically allow you to reuse settings as-is because you can use the same subchain of nodes multiple times in the main chain. I haven't added any examples yet, but you can see me using them in that silly video I recently posted (which got way more views than the not-silly videos before it).

The way modules would work in this case is that when you set up one of the completion nodes a certain way, you just connect it into a ModuleIO node and you reuse that same node (+ any others attached to it) via a Module node as many times as you want, so you don't need what you described just for this type of reuse.

**Comment by DatCaptainHorse** [comment]
Ah! Yeah module nodes seem to do what I want for 2nd idea, still learning the system :sweat_smile:
I've recently coded only in Go so that's why I was looking for easy `-1` as index, if you can do that and try the others, I'd appreciate it!

**Comment by zenoverflow** [comment]
The negative indices are now supported on the array picker nodes. Remembered I had to modify the labels on OpenAI nodes to make it obvious they output arrays (people were getting confused despite the visibly different color of the connection) so I bundled those changes together in another minor update.

**Comment by zenoverflow** [comment]
Added TextReplace and TextReplaceRegex nodes with start index and limit options.

I'm planning on adding that override capability as a global enable-on-demand feature for each node, where the dev making the node (hence me and/or anybody using the custom nodes feature) could optionally specify an override map of `Field -> PropertyName`.

If this map is provided by the dev, a string input named `override` would automatically get added to each node in order to receive a JSON object with overrides for each field, and the execution engine would automatically use the input (if connected) and the map to correctly replace values on the node's controls.

The override map would also be used to generate more documentation that tells users what fields they can pass in via the external JSON object, whether it's LLM-generated or not.

Such an implementation would avoid 3 huge nuisances in regards to controls (settings):
- Renaming labels on controls to be the same as the underlying properties to let people know what to put into the JSON object
- Making people uber-confused because said properties are meant for devs and are not necessarily as descriptive as the labels
- Being a target of epic spam when OmniChain gets more adoption, by people eventually pointing out that ComfyUI has the ability to convert controls into inputs

For now I have no idea whether some random technical detail that I forgot about could stop me from implementing this. Hopefully not, because the increase in workflow flexibility would be massive.

Your opinion on this would be greatly appreciated btw, it's an evolution of your idea after all.

**Comment by DatCaptainHorse** [comment]
Thanks for the replacement nodes!

As for your implementation thoughts on overrides, I don't see anything immediately popout that would be an issue :thinking: - so it looks good to me :+1:

**Comment by zenoverflow** [comment]
The override feature is live. I think that's it for now, so I'm probably closing this thread tomorrow.

Everything went according to plan, just had to add a separate helper method in the execution context that nodes receive because touching the old one would break compatibility for any custom nodes people have built for themselves and I don't want to be that guy.

Had to make another update anyway thanks to CodeMirror (the editor in the large modal popup when you click the expand button on text nodes) somehow disabling the keyboard on Chromium-based browsers even after it was closed. Now using `react-simple-code-editor`.

Dang, who knows how many people got turned off the app because of CodeMirror, right when I'm looking for investment.

I wonder who the lead dev of CodeMirror is.

"I just wanna talk to him."
