### ISSUE TITLE
Request for More Detailed Documentation: Step-by-Step Guide for Building Chains

### ISSUE THREAD

**Issue by SamuelDevdas** [zenoverflow/omnichain#14]
First of all, thank you for providing OmniChain—it seems like a very powerful framework with a lot of potential. However, as someone new to this framework, I'm finding it difficult to get started due to gaps in the documentation. I hope my feedback can help improve the learning experience for new users like myself.

In particular, I am struggling with the following areas:

- **Lack of Clear Starting Point:** The documentation doesn’t provide an obvious place to start for beginners who are building their first chain. I am unsure of which node to begin with and how to structure the workflow logically.

- **Missing Step-by-Step Instructions:** While the examples provided are helpful, they seem to skip over important foundational steps. After adding a node, there is no clear guidance on what the next step should be, making the process harder to follow.

- **Unclear Node Connections:** The documentation doesn’t explain how the various nodes connect and what their relationships are. For instance, the input/output flow between nodes such as `TextField`, `OllamaTextCompletion`, and others like `CheckForNextMessage` isn’t well explained.

In my attempt to build a basic workflow (with a simple text input to generate responses using Ollama), I ran into issues that could have been resolved with more detailed documentation (see attached images).

**Suggestions:**

- **Provide a Step-by-Step Getting Started Guide:** 
  - Start with the basics and walk beginners through building a simple chain. 
  - Break down the purpose of key nodes like `TextField`, `OllamaTextCompletion`, `CheckForNextMessage`, and `Response`.

- **Explain Logical Flow Between Nodes:**
  - A detailed explanation of how nodes connect and interact would help. 
  - Diagrams or more detailed visual aids to show the connections between nodes, along with descriptions of input/output flows, would make the learning curve smoother.

- **Enhance Existing Examples:** 
  - Provide more annotations or comments on the chat example, explaining what each node does and how they work together.
  - Consider offering simplified examples, focusing on one key concept at a time before moving into more complex workflows.

**Reproduction:**

1. I tried creating a basic workflow using `TextField` and `OllamaTextCompletion` for text input and output.
2. I struggled to find a clear starting point and couldn't determine what the next steps should be after adding each node.
3. I was unsure of how to connect the nodes logically.
4. Screenshots attached to illustrate the difficulties I encountered.

**Screenshots:**
![image](https://github.com/user-attachments/assets/ad43b47e-6313-4b2b-8861-e5f35f8d787d)
![image](https://github.com/user-attachments/assets/99ecb050-fb09-435d-849a-3b72fd04a87c)

1. My workflow attempt: Shows where I faced confusion in terms of connecting nodes and the next steps.
2. Documentation example: Highlights the areas that could use more explanation.

**Expected Behavior:**

- **A Clear Starting Point:** The documentation should guide users from the ground up, showing where to start and what to expect.
  
- **Logical Flow Between Steps:** A step-by-step explanation of what to do after adding each node and why.

- **Node Connection Clarity:** Clear guidance on how to connect nodes, with explanations of their inputs, outputs, and interactions.

Once again, I appreciate the work that has gone into OmniChain, and I hope these suggestions can help make the learning process more accessible to newcomers.

**Comment by zenoverflow** [comment]
I'll make a simpler quick-start section in the docs as soon as I can, but let me point out something really critical (or really stupid) - *there is absolutely no relationship between the nodes*. None. Zero. Nada.

The only rules are that you have to match the connection colors, inputs are on the left, outputs are on the right, and red sockets are "special" because they run logic from left to right, while every other color of socket does "node on the right requests data from one or more nodes on the left" like ComfyUI.

There are some engine-level limitations I already point out in the docs like:
- Trigger (red) sockets can only produce a single connection as outputs but accept multiple connections as inputs
- Data sockets (not red) can usually have multiple output connections, and whoever wrote the node can also allow multiple input connections.

And... that's it. You're not finding a logical way to connect anything because there isn't any. You create your own logic, just like a programming language.

I guess I really messed up by building a no-code project with coding levels of complexity. Should've just made an extension to Scratch or something. Or maybe I should've just studied to be a psychiatrist or become a memetuber, possibly both. Park ranger sounds like a nice job when you're a nihilist and you fear no bear (or moose).

Anyway, yeah I'll work on a cleaner quick-start guide for beginners.

**Comment by zenoverflow** [comment]
Added a quick-start guide to the docs [here](https://omnichain.zenoverflow.com/docs/quick-start-guide). Probably won't make the project any less confusing. I mean, seriously, what am I even doing. Big corpo is eventually going to have their models spitting Python to build workflows and decision trees on their own. Zuck can get one of his teams to build something better than this in like 3 days. Closing this issue to go rethink my life.
