### ISSUE TITLE
SyntaxError: The requested module './_Base' does not provide an export named 'makeNode'

### ISSUE THREAD

**Issue by vmajor** [zenoverflow/omnichain#2]
Macos Sonoma 14.5

Fresh node.js install, updated npm to the latest available version.

When running 'npm run serve' I get the following error

```
SyntaxError: The requested module './_Base' does not provide an export named 'makeNode'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

**Comment by zenoverflow** [comment]
Weird. It's possible your install somehow got corrupted, or you have some issues with file permissions that prevent your system from reading that file properly. I just re-tested the app on my old Mac and I can't reproduce the issue.

Try nuking the entire thing and setting it up in a random different empty folder in ~/Downloads, then run `chown -R yourUser .` in the parent folder just in case, then tell me what happens.

Also, I know for a fact that the export is there, pretty central piece of code in fact, which is why I said the error is weird.

**Comment by vmajor** [comment]
Lol that worked. Nuked it all, including npm, then reinstalled. This type of fix is like "have you tried turning it off and on again"...

Thank you for the advice :)
